### ISSUE TITLE
#TODO dump

### ISSUE THREAD

**Issue by sirbrad** [sirbrad/vuejs-address-book#1]
A dump of **TODOS** to get through;

- [x] Flexbox layout
- [ ] Slight bit of style on the user-show
- [ ] Router-link active state
- [ ] Router component transition
- [ ] Filtering
- [ ] Add other views (#edit & #new)
- [ ] Unit testing
- [ ] Adding Vuex
